# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optitype_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#------------------------pyQt imports-----------------------
from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtCore import QTimer
from PyQt5.QtGui import QImage, QPixmap
#----------------opencv imports---------------------------------
import sys
import cv2
import numpy as np
import dlib
from math import hypot




#-----------------Ui Management------------------------
class Ui_MainWindow(object):
    def __init__(self,MainWindow):
        super().__init__()

        # Initialize EyeDetection with reference to this UI
        self.eye_detector = EyeDetection("shape_predictor_68_face_landmarks.dat",self)

        self.setupUi()
        self.MainWindow = MainWindow

        #time counter variable
        self.time_count = 0

       
        

    def setupUi(self):
       
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1264, 759)
        MainWindow.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.329545, x2:1, y2:0, stop:0.0894737 rgba(0, 117, 184, 255), stop:0.884211 rgba(255, 255, 255, 255));")
        
         

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.keyboard = QtWidgets.QFrame(self.centralwidget)
        self.keyboard.setGeometry(QtCore.QRect(110, 470, 821, 220))
        self.keyboard.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius: 20px;")
        self.keyboard.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.keyboard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keyboard.setObjectName("keyboard")

        #------------------experimental section----------------------------------------

        # OptiType keyboard layout
        self.keyboard_layout = [
            ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],  # Row 0
            ['J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R'],  # Row 1
            ['S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ']   # Row 2
        ]
        
        # Keyboard Buttons
        self.keyboard_buttons = []
        for i, row in enumerate(self.keyboard_layout):
            self.button_row = []
            for j, letter in enumerate(row):
                self.a_button = QtWidgets.QFrame(self.keyboard)
                self.a_button.setGeometry(QtCore.QRect(10 + j * 90, 10 + i * 70, 61, 61))
                self.a_button.setStyleSheet("background-color: rgb(255, 255, 255);")
                self.a_button.setFrameShape(QtWidgets.QFrame.WinPanel)
                self.a_button.setFrameShadow(QtWidgets.QFrame.Raised)
                self.a_button.setLineWidth(7)
                self.a_button.setObjectName("a_button")

                #alphabet adding
                self.letter_a = QtWidgets.QLabel(self.a_button)
                self.letter_a.setGeometry(QtCore.QRect(10, 10, 31, 31))
                font = QtGui.QFont()
                font.setPointSize(24)
                font.setBold(True)
                font.setWeight(75)
                self.letter_a.setFont(font)
                self.letter_a.setStyleSheet("color: rgb(85, 85, 255);")
                self.letter_a.setFrameShadow(QtWidgets.QFrame.Plain)
                self.letter_a.setObjectName("letter_a")
                self.letter_a.setText( letter)

            self.keyboard_buttons.append(self.button_row)


        #------------------^^^ experimental section ends ^^^----------------------------------------

        """
        self.a_button = QtWidgets.QFrame(self.keyboard)
        self.a_button.setGeometry(QtCore.QRect(20, 10, 61, 60))
        self.a_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.a_button.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.a_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.a_button.setLineWidth(7)
        self.a_button.setObjectName("a_button")
        self.letter_a = QtWidgets.QLabel(self.a_button)
        self.letter_a.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.letter_a.setFont(font)
        self.letter_a.setStyleSheet("color: rgb(85, 85, 255);")
        self.letter_a.setFrameShadow(QtWidgets.QFrame.Plain)
        self.letter_a.setObjectName("letter_a")
        
        self.s_button = QtWidgets.QFrame(self.keyboard)
        self.s_button.setGeometry(QtCore.QRect(90, 10, 61, 60))
        self.s_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.s_button.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.s_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.s_button.setLineWidth(7)
        self.s_button.setObjectName("s_button")
        self.letter_s = QtWidgets.QLabel(self.s_button)
        self.letter_s.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.letter_s.setFont(font)
        self.letter_s.setStyleSheet("color: rgb(85, 85, 255);")
        self.letter_s.setFrameShadow(QtWidgets.QFrame.Plain)
        self.letter_s.setObjectName("letter_s")
        
        self.d_button = QtWidgets.QFrame(self.keyboard)
        self.d_button.setGeometry(QtCore.QRect(160, 10, 61, 60))
        self.d_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_button.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.d_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.d_button.setLineWidth(7)
        self.d_button.setObjectName("d_button")
        self.letter_d = QtWidgets.QLabel(self.d_button)
        self.letter_d.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.letter_d.setFont(font)
        self.letter_d.setStyleSheet("color: rgb(85, 85, 255);")
        self.letter_d.setFrameShadow(QtWidgets.QFrame.Plain)
        self.letter_d.setObjectName("letter_d")

        self.f_button = QtWidgets.QFrame(self.keyboard)
        self.f_button.setGeometry(QtCore.QRect(230, 10, 61, 60))
        self.f_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f_button.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.f_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_button.setLineWidth(7)
        self.f_button.setObjectName("f_button")
        self.letter_f = QtWidgets.QLabel(self.f_button)
        self.letter_f.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.letter_f.setFont(font)
        self.letter_f.setStyleSheet("color: rgb(85, 85, 255);")
        self.letter_f.setFrameShadow(QtWidgets.QFrame.Plain)
        self.letter_f.setObjectName("letter_f")

        self.back_button = QtWidgets.QFrame(self.keyboard)
        self.back_button.setGeometry(QtCore.QRect(320, 10, 61, 60))
        self.back_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.back_button.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.back_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.back_button.setLineWidth(7)
        self.back_button.setObjectName("back_button")
        self.backspace = QtWidgets.QLabel(self.back_button)
        self.backspace.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.backspace.setFont(font)
        self.backspace.setStyleSheet("color: rgb(85, 85, 255);")
        self.backspace.setFrameShadow(QtWidgets.QFrame.Plain)
        self.backspace.setObjectName("backspace")

        self.clear_button = QtWidgets.QFrame(self.keyboard)
        self.clear_button.setGeometry(QtCore.QRect(400, 10, 61, 60))
        self.clear_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.clear_button.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.clear_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.clear_button.setLineWidth(7)
        self.clear_button.setObjectName("clear_button")
        self.clear_Button = QtWidgets.QLabel(self.clear_button)
        self.clear_Button.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.clear_Button.setFont(font)
        self.clear_Button.setStyleSheet("color: rgb(255, 0, 0);")
        self.clear_Button.setFrameShadow(QtWidgets.QFrame.Plain)
        self.clear_Button.setObjectName("clear_Button")
        """

        self.word_palette = QtWidgets.QFrame(self.centralwidget)
        self.word_palette.setGeometry(QtCore.QRect(110, 390, 821, 71))
        self.word_palette.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.word_palette.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.word_palette.setFrameShadow(QtWidgets.QFrame.Raised)
        self.word_palette.setObjectName("word_palette")
        self.word1 = QtWidgets.QLabel(self.word_palette)
        self.word1.setEnabled(True)
        self.word1.setGeometry(QtCore.QRect(50, 15, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.word1.setFont(font)
        self.word1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.word1.setAlignment(QtCore.Qt.AlignCenter)
        self.word1.setObjectName("word1")
        self.word2 = QtWidgets.QLabel(self.word_palette)
        self.word2.setEnabled(True)
        self.word2.setGeometry(QtCore.QRect(230, 15, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.word2.setFont(font)
        self.word2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.word2.setAlignment(QtCore.Qt.AlignCenter)
        self.word2.setObjectName("word2")
        self.word3 = QtWidgets.QLabel(self.word_palette)
        self.word3.setEnabled(True)
        self.word3.setGeometry(QtCore.QRect(430, 15, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.word3.setFont(font)
        self.word3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.word3.setAlignment(QtCore.Qt.AlignCenter)
        self.word3.setObjectName("word3")
        self.word4 = QtWidgets.QLabel(self.word_palette)
        self.word4.setEnabled(True)
        self.word4.setGeometry(QtCore.QRect(610, 15, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.word4.setFont(font)
        self.word4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.word4.setAlignment(QtCore.Qt.AlignCenter)
        self.word4.setObjectName("word4")
        self.Text_Display = QtWidgets.QFrame(self.centralwidget)
        self.Text_Display.setGeometry(QtCore.QRect(110, 140, 821, 141))
        self.Text_Display.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Text_Display.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Text_Display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Text_Display.setObjectName("Text_Display")
        self.Text_area = QtWidgets.QLabel(self.Text_Display)
        self.Text_area.setGeometry(QtCore.QRect(20, 10, 781, 111))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Text_area.setFont(font)
        self.Text_area.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Text_area.setObjectName("Text_area")

        self.up_button = QtWidgets.QFrame(self.centralwidget)
        self.up_button.setGeometry(QtCore.QRect(260, 309, 71, 61))
        self.up_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid black;\n"
"border-radius: 20px;\n"
"")
        self.up_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.up_button.setFrameShadow(QtWidgets.QFrame.Plain)
        self.up_button.setObjectName("up_button")
        self.up_icon = QtWidgets.QLabel(self.up_button)
        self.up_icon.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.up_icon.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.up_icon.setText("")
        self.up_icon.setPixmap(QtGui.QPixmap("./images/up.png"))
        self.up_icon.setScaledContents(True)
        self.up_icon.setObjectName("up_icon")

        self.left_button = QtWidgets.QFrame(self.centralwidget)
        self.left_button.setGeometry(QtCore.QRect(350, 310, 71, 61))
        self.left_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid black;\n"
"border-radius: 20px;\n"
"")
        self.left_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_button.setFrameShadow(QtWidgets.QFrame.Plain)
        self.left_button.setObjectName("left_button")
        self.left_icon = QtWidgets.QLabel(self.left_button)
        self.left_icon.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.left_icon.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.left_icon.setText("")
        self.left_icon.setPixmap(QtGui.QPixmap("./images/left.png"))
        self.left_icon.setScaledContents(True)
        self.left_icon.setObjectName("left_icon")
        
        self.ok_button = QtWidgets.QFrame(self.centralwidget)
        self.ok_button.setGeometry(QtCore.QRect(440, 310, 71, 61))
        self.ok_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid black;\n"
"border-radius: 20px;\n"
"")
        self.ok_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ok_button.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ok_button.setObjectName("ok_button")
        self.ok_icon = QtWidgets.QLabel(self.ok_button)
        self.ok_icon.setGeometry(QtCore.QRect(4, 5, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(17)
        self.ok_icon.setFont(font)
        self.ok_icon.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.ok_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.ok_icon.setObjectName("ok_icon")

        self.right_button = QtWidgets.QFrame(self.centralwidget)
        self.right_button.setGeometry(QtCore.QRect(530, 310, 71, 61))
        self.right_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid black;\n"
"border-radius: 20px;\n"
"")
        self.right_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_button.setFrameShadow(QtWidgets.QFrame.Plain)
        self.right_button.setObjectName("right_button")
        self.right_icon = QtWidgets.QLabel(self.right_button)
        self.right_icon.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.right_icon.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.right_icon.setText("")
        self.right_icon.setPixmap(QtGui.QPixmap("./images/right.png"))
        self.right_icon.setScaledContents(True)
        self.right_icon.setObjectName("right_icon")
        self.down_button = QtWidgets.QFrame(self.centralwidget)
        self.down_button.setGeometry(QtCore.QRect(620, 310, 71, 61))
        self.down_button.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid black;\n"
"border-radius: 20px;\n"
"")
        self.down_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.down_button.setFrameShadow(QtWidgets.QFrame.Plain)
        self.down_button.setObjectName("down_button")
        self.down_icon = QtWidgets.QLabel(self.down_button)
        self.down_icon.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.down_icon.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.down_icon.setText("")      
        self.down_icon.setPixmap(QtGui.QPixmap("./images/down.png"))
        self.down_icon.setScaledContents(True)
        self.down_icon.setObjectName("down_icon")
        self.voice_button = QtWidgets.QFrame(self.centralwidget)
        self.voice_button.setGeometry(QtCore.QRect(710, 310, 61, 61))
        self.voice_button.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"")
        self.voice_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.voice_button.setFrameShadow(QtWidgets.QFrame.Plain)
        self.voice_button.setObjectName("voice_button")
        self.voice_icon = QtWidgets.QLabel(self.voice_button)
        self.voice_icon.setGeometry(QtCore.QRect(-30, -26, 121, 111))
        self.voice_icon.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.voice_icon.setText("")
        self.voice_icon.setPixmap(QtGui.QPixmap("./images/voice_icon.png"))
        self.voice_icon.setScaledContents(True)
        self.voice_icon.setObjectName("voice_icon")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(20, -60, 261, 231))
        self.logo_label.setStyleSheet("background-color: transparent;")
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("./images/logo.png"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.video_view = QtWidgets.QFrame(self.centralwidget)
        self.video_view.setGeometry(QtCore.QRect(940, 10, 311, 691))
        self.video_view.setStyleSheet("\n"
"background-color: white")
        self.video_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.video_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.video_view.setObjectName("video_view")
        self.label = QtWidgets.QLabel(self.video_view)
        self.label.setGeometry(QtCore.QRect(20, 40, 281, 191))
        self.label.setStyleSheet("border: 2px solid black;\n"
"    background-color: #f0f0f0;")
        self.label.setText("")

        #########################################################


        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1264, 26))
        self.menubar.setObjectName("menubar")
        self.hlo = QtWidgets.QMenu(self.menubar)
        self.hlo.setObjectName("hlo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.hlo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


#----------------setting timer----------------------
        self.timer = QTimer()
        self.timer.timeout.connect(self.update_frame)
        self.cap = cv2.VideoCapture(0)
        self.timer.start(30)


#---------------------frame update function------------------------
    def update_frame(self):
        ret, frame = self.cap.read()
        if ret:
            frame = self.eye_detector.process_frame(frame)
            frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

         # Resize the frame to match the QLabel size
            label_width = self.label.width()
            label_height = self.label.height()
            frame = cv2.resize(frame, (label_width, label_height), interpolation=cv2.INTER_AREA)

            h, w, ch = frame.shape
            qimg = QImage(frame.data, w, h, ch * w, QImage.Format_RGB888)
            self.label.setPixmap(QPixmap.fromImage(qimg))

#---------------update text area function--------------------------------
    def update_text_area(self, text):
        """Update the text in the text area."""
        self.Text_area.setText(text)
        

#-----------highlight navigation buttons------------------------------------
    def update_highlight(self,current_btn):
        """Highlight the current key and reset others."""
        self.nav = [self.up_button,self.left_button,self.ok_button,self.right_button,self.down_button]
        for i, btn in enumerate(self.nav):
                if i == current_btn :#current_btn initialised as 0 in the constructor of eyeDetector class
                        btn.setStyleSheet("background-color: blue;\n"
                "border: 2px solid black;\n"
                "border-radius: 20px;\n"
                "")  # Highlight
                else:
                        #btn.setStyleSheet("background-color: lightgray;")  # Default
                        btn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
                "border: 2px solid black;\n"
                "border-radius: 20px;\n"
                "")
                        btn.setFrameShape(QtWidgets.QFrame.NoFrame)
                        btn.setFrameShadow(QtWidgets.QFrame.Plain)
                        

#-----------highlight keyboard buttons------------------------------------(not complete)
    def update_highlight_keyboard(self,current_btn):
        """Highlight the current key and reset others."""
        
        for i, row in enumerate(self.keyboard_buttons):
            for j, button in enumerate(row):
                if i == self.current_row and j == self.current_col:
                    button.setStyleSheet("background-color: yellow;")  # Highlight
                else:
                    button.setStyleSheet("background-color: lightgray;")  # Default


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        #self.letter_a.setText(_translate("MainWindow", "A"))
        #these are commented to try to generate keyboard using loop
        '''
        self.letter_s.setText(_translate("MainWindow", "S"))
        self.letter_d.setText(_translate("MainWindow", "D"))
        self.letter_f.setText(_translate("MainWindow", "F"))
        self.backspace.setText(_translate("MainWindow", "<"))
        self.clear_Button.setText(_translate("MainWindow", "C"))
        '''
        self.word1.setText(_translate("MainWindow", "Word 1"))
        self.word2.setText(_translate("MainWindow", "Word 2"))
        self.word3.setText(_translate("MainWindow", "Word 3"))
        self.word4.setText(_translate("MainWindow", "Word 4"))
        self.Text_area.setText(_translate("MainWindow", "Your text will be displayed here.."))
        self.ok_icon.setText(_translate("MainWindow", "OK"))
        self.hlo.setTitle(_translate("MainWindow", "Assist"))

#---------------Close Event------------------------------------    
    def closeEvent(self, event):
        self.cap.release()
        cv2.destroyAllWindows()
        event.accept()


#------------Eye Detection------------------------------
class EyeDetection:
    def __init__(self, shape_predictor_path, ui):
        self.detector = dlib.get_frontal_face_detector()
        self.predictor = dlib.shape_predictor(shape_predictor_path)
        self.font = cv2.FONT_HERSHEY_COMPLEX
#--------------initiating ui-------------------------------
        self.ui = ui
#----------current button to navigate buttons-----------------
        self.current_btn = 0
        self.left_frame = 0
        self.right_frame = 0
        self.blinking_frame = 0

    @staticmethod
    def midpoint(p1, p2):
        return int((p1.x + p2.x) / 2), int((p1.y + p2.y) / 2)

    def get_blinking_ratio(self, eye_points, facial_landmarks):
        right_point = (facial_landmarks.part(eye_points[0]).x, facial_landmarks.part(eye_points[0]).y)
        left_point = (facial_landmarks.part(eye_points[3]).x, facial_landmarks.part(eye_points[3]).y)
        center_top = self.midpoint(facial_landmarks.part(eye_points[1]), facial_landmarks.part(eye_points[2]))
        bottom_top = self.midpoint(facial_landmarks.part(eye_points[5]), facial_landmarks.part(eye_points[4]))

        hor_line_length = hypot((left_point[0] - right_point[0]), (left_point[1] - right_point[1]))
        ver_line_length = hypot((center_top[0] - bottom_top[0]), (center_top[1] - bottom_top[1]))

        return hor_line_length / ver_line_length

    def get_gaze_ratio(self, eye_points, facial_landmarks, frame, gray):
        eye_region = np.array([
            (facial_landmarks.part(eye_points[0]).x, facial_landmarks.part(eye_points[0]).y),
            (facial_landmarks.part(eye_points[1]).x, facial_landmarks.part(eye_points[1]).y),
            (facial_landmarks.part(eye_points[2]).x, facial_landmarks.part(eye_points[2]).y),
            (facial_landmarks.part(eye_points[3]).x, facial_landmarks.part(eye_points[3]).y),
            (facial_landmarks.part(eye_points[4]).x, facial_landmarks.part(eye_points[4]).y),
            (facial_landmarks.part(eye_points[5]).x, facial_landmarks.part(eye_points[5]).y)
        ])

        height, width, _ = frame.shape
        mask = np.zeros((height, width), np.uint8)
        cv2.polylines(mask, [eye_region], True, 255, 2)
        cv2.fillPoly(mask, [eye_region], 255)

        eye = cv2.bitwise_and(gray, gray, mask=mask)

        min_x = np.min(eye_region[:, 0])
        max_x = np.max(eye_region[:, 0])
        min_y = np.min(eye_region[:, 1])
        max_y = np.max(eye_region[:, 1])

        gray_eye = eye[min_y:max_y, min_x:max_x]
        _, threshold_eye = cv2.threshold(gray_eye, 70, 255, cv2.THRESH_BINARY)

        height, width = threshold_eye.shape
        left_side_threshold = threshold_eye[0:height, 0:int(width / 2)]
        right_side_threshold = threshold_eye[0:height, int(width / 2):width]

        left_side_white = cv2.countNonZero(left_side_threshold)
        right_side_white = cv2.countNonZero(right_side_threshold)

        return left_side_white / (right_side_white + 0.000000001)

    def process_frame(self, frame):
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = self.detector(gray)

        for face in faces:
            self.ui.update_highlight(self.current_btn)

            landmarks = self.predictor(gray, face)

            left_eye_ratio = self.get_blinking_ratio([36, 37, 38, 39, 40, 41], landmarks)
            right_eye_ratio = self.get_blinking_ratio([42, 43, 44, 45, 46, 47], landmarks)
            blinking_ratio = (left_eye_ratio + right_eye_ratio) / 2

            if blinking_ratio > 5.7:
                cv2.putText(frame, "BLINKING", (50, 150), self.font, 3, (255, 255, 0))
                self.blinking_frame += 1
                if(self.blinking_frame > 10):
                     self.ui.word1.setText(f"{self.current_btn}")
            else:
                self.blinking_frame = 0
                #made the gaze detection inside the else using one tab space--undo if needed
                gaze_ratio_left_eye = self.get_gaze_ratio([36, 37, 38, 39, 40, 41], landmarks, frame, gray)
                gaze_ratio_right_eye = self.get_gaze_ratio([42, 43, 44, 45, 46, 47], landmarks, frame, gray)
                gaze_ratio = (gaze_ratio_left_eye + gaze_ratio_right_eye) / 2

                if gaze_ratio < 1:
                        cv2.putText(frame, "RIGHT", (50, 100), self.font, 2, (0, 0, 255), 3)
                        #when left we need to do left transition over the buttons
                        self.ui.update_text_area("Looking RIGHT")


                        #moving nav btn with time lag
                        self.left_frame = 0
                        self.right_frame += 1
                        if(self.right_frame>10):
                                self.right_frame = 0
                                if(self.current_btn <= 3 ):
                                        self.current_btn+=1
                
                        '''
                        if(self.frame_count!=0):
                        self.frame_count=0
                        else:
                        self.frame_count +=1
                        self.ui.word1.setText(f"{self.frame_count}")
                        '''

                        

                elif 1 < gaze_ratio < 3:
                        cv2.putText(frame, "CENTER", (50, 100), self.font, 2, (255, 0, 255), 3)
                        self.left_frame = 0
                        self.right_frame = 0
                else:
                        cv2.putText(frame, "LEFT", (50, 100), self.font, 2, (0, 255, 255), 3)
                        self.ui.update_text_area("Looking LEFT")
                        
                        #moving nav btn with time lag
                        self.right_frame=0
                        self.left_frame+=1
                        if(self.left_frame>10):
                                self.left_frame = 0
                                if(self.current_btn != 0):
                                        self.current_btn-=1

        return frame


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(MainWindow)
    #ui.setupUi(MainWindow)
    MainWindow.showMaximized()  # This makes the window full-screen.
    #MainWindow.show()
    sys.exit(app.exec_())
