# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'optitype.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1070, 759)
        MainWindow.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.329545, x2:1, y2:0, stop:0.0894737 rgba(0, 117, 184, 255), stop:0.884211 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.keyboard = QtWidgets.QFrame(self.centralwidget)
        self.keyboard.setGeometry(QtCore.QRect(110, 470, 821, 211))
        self.keyboard.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"border-radius: 20px;")
        self.keyboard.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.keyboard.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keyboard.setObjectName("keyboard")
        self.alpha_button = QtWidgets.QFrame(self.keyboard)
        self.alpha_button.setGeometry(QtCore.QRect(20, 10, 61, 60))
        self.alpha_button.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.alpha_button.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.alpha_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alpha_button.setLineWidth(7)
        self.alpha_button.setObjectName("alpha_button")
        self.letter_a = QtWidgets.QLabel(self.alpha_button)
        self.letter_a.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.letter_a.setFont(font)
        self.letter_a.setStyleSheet("color: rgb(85, 85, 255);")
        self.letter_a.setFrameShadow(QtWidgets.QFrame.Plain)
        self.letter_a.setObjectName("letter_a")
        self.alpha_button_2 = QtWidgets.QFrame(self.keyboard)
        self.alpha_button_2.setGeometry(QtCore.QRect(90, 10, 61, 60))
        self.alpha_button_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.alpha_button_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.alpha_button_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alpha_button_2.setLineWidth(7)
        self.alpha_button_2.setObjectName("alpha_button_2")
        self.letter_a_2 = QtWidgets.QLabel(self.alpha_button_2)
        self.letter_a_2.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.letter_a_2.setFont(font)
        self.letter_a_2.setStyleSheet("color: rgb(85, 85, 255);")
        self.letter_a_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.letter_a_2.setObjectName("letter_a_2")
        self.alpha_button_3 = QtWidgets.QFrame(self.keyboard)
        self.alpha_button_3.setGeometry(QtCore.QRect(160, 10, 61, 60))
        self.alpha_button_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.alpha_button_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.alpha_button_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alpha_button_3.setLineWidth(7)
        self.alpha_button_3.setObjectName("alpha_button_3")
        self.letter_a_5 = QtWidgets.QLabel(self.alpha_button_3)
        self.letter_a_5.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.letter_a_5.setFont(font)
        self.letter_a_5.setStyleSheet("color: rgb(85, 85, 255);")
        self.letter_a_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.letter_a_5.setObjectName("letter_a_5")
        self.alpha_button_4 = QtWidgets.QFrame(self.keyboard)
        self.alpha_button_4.setGeometry(QtCore.QRect(230, 10, 61, 60))
        self.alpha_button_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.alpha_button_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.alpha_button_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alpha_button_4.setLineWidth(7)
        self.alpha_button_4.setObjectName("alpha_button_4")
        self.letter_a_6 = QtWidgets.QLabel(self.alpha_button_4)
        self.letter_a_6.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.letter_a_6.setFont(font)
        self.letter_a_6.setStyleSheet("color: rgb(85, 85, 255);")
        self.letter_a_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.letter_a_6.setObjectName("letter_a_6")
        self.alpha_button_9 = QtWidgets.QFrame(self.keyboard)
        self.alpha_button_9.setGeometry(QtCore.QRect(320, 10, 61, 60))
        self.alpha_button_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.alpha_button_9.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.alpha_button_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alpha_button_9.setLineWidth(7)
        self.alpha_button_9.setObjectName("alpha_button_9")
        self.letter_a_11 = QtWidgets.QLabel(self.alpha_button_9)
        self.letter_a_11.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.letter_a_11.setFont(font)
        self.letter_a_11.setStyleSheet("color: rgb(85, 85, 255);")
        self.letter_a_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.letter_a_11.setObjectName("letter_a_11")
        self.alpha_button_10 = QtWidgets.QFrame(self.keyboard)
        self.alpha_button_10.setGeometry(QtCore.QRect(400, 10, 61, 60))
        self.alpha_button_10.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.alpha_button_10.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.alpha_button_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.alpha_button_10.setLineWidth(7)
        self.alpha_button_10.setObjectName("alpha_button_10")
        self.letter_a_12 = QtWidgets.QLabel(self.alpha_button_10)
        self.letter_a_12.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.letter_a_12.setFont(font)
        self.letter_a_12.setStyleSheet("color: rgb(255, 0, 0);")
        self.letter_a_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.letter_a_12.setObjectName("letter_a_12")
        self.word_palette = QtWidgets.QFrame(self.centralwidget)
        self.word_palette.setGeometry(QtCore.QRect(110, 390, 821, 71))
        self.word_palette.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"border-radius: 20px;")
        self.word_palette.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.word_palette.setFrameShadow(QtWidgets.QFrame.Raised)
        self.word_palette.setObjectName("word_palette")
        self.word1 = QtWidgets.QLabel(self.word_palette)
        self.word1.setEnabled(True)
        self.word1.setGeometry(QtCore.QRect(50, 15, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.word1.setFont(font)
        self.word1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.word1.setAlignment(QtCore.Qt.AlignCenter)
        self.word1.setObjectName("word1")
        self.word2 = QtWidgets.QLabel(self.word_palette)
        self.word2.setEnabled(True)
        self.word2.setGeometry(QtCore.QRect(230, 15, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.word2.setFont(font)
        self.word2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.word2.setAlignment(QtCore.Qt.AlignCenter)
        self.word2.setObjectName("word2")
        self.word3 = QtWidgets.QLabel(self.word_palette)
        self.word3.setEnabled(True)
        self.word3.setGeometry(QtCore.QRect(430, 15, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.word3.setFont(font)
        self.word3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.word3.setAlignment(QtCore.Qt.AlignCenter)
        self.word3.setObjectName("word3")
        self.word4 = QtWidgets.QLabel(self.word_palette)
        self.word4.setEnabled(True)
        self.word4.setGeometry(QtCore.QRect(610, 15, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.word4.setFont(font)
        self.word4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.word4.setAlignment(QtCore.Qt.AlignCenter)
        self.word4.setObjectName("word4")
        self.Text_Display = QtWidgets.QFrame(self.centralwidget)
        self.Text_Display.setGeometry(QtCore.QRect(110, 140, 821, 141))
        self.Text_Display.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Text_Display.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.Text_Display.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Text_Display.setObjectName("Text_Display")
        self.Text_area = QtWidgets.QLabel(self.Text_Display)
        self.Text_area.setGeometry(QtCore.QRect(20, 10, 781, 111))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.Text_area.setFont(font)
        self.Text_area.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Text_area.setObjectName("Text_area")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(260, 309, 71, 61))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid black;\n"
"border-radius: 20px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.label.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("H:/downloads/up-removebg-preview.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(350, 310, 71, 61))
        self.frame_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid black;\n"
"border-radius: 20px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.label_3.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("H:/downloads/left-removebg-preview.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(440, 310, 71, 61))
        self.frame_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid black;\n"
"border-radius: 20px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(4, 5, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(17)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(530, 310, 71, 61))
        self.frame_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid black;\n"
"border-radius: 20px;\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.label_4.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("H:/downloads/right-removebg-preview.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(620, 310, 71, 61))
        self.frame_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.568, y1:0.636727, x2:1, y2:1, stop:0 rgba(201, 229, 255, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid black;\n"
"border-radius: 20px;\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 51, 41))
        self.label_5.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("H:/downloads/down-removebg-preview.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(710, 310, 61, 61))
        self.frame_6.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border: 2px solid black;\n"
"border-radius: 30px;\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(-30, -26, 121, 111))
        self.label_6.setStyleSheet("background-color: transparent;\n"
"border: opx;\n"
"border-radius: 0px;\n"
"")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("H:/downloads/images-removebg-preview.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, -60, 261, 231))
        self.label_2.setStyleSheet("background-color: transparent;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("H:/downloads/LOGO-removebg-preview.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1070, 26))
        self.menubar.setObjectName("menubar")
        self.menud2d2d2d2d2d2 = QtWidgets.QMenu(self.menubar)
        self.menud2d2d2d2d2d2.setObjectName("menud2d2d2d2d2d2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menud2d2d2d2d2d2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.letter_a.setText(_translate("MainWindow", "A"))
        self.letter_a_2.setText(_translate("MainWindow", "S"))
        self.letter_a_5.setText(_translate("MainWindow", "D"))
        self.letter_a_6.setText(_translate("MainWindow", "F"))
        self.letter_a_11.setText(_translate("MainWindow", "<"))
        self.letter_a_12.setText(_translate("MainWindow", "C"))
        self.word1.setText(_translate("MainWindow", "Word 1"))
        self.word2.setText(_translate("MainWindow", "Word 2"))
        self.word3.setText(_translate("MainWindow", "Word 3"))
        self.word4.setText(_translate("MainWindow", "Word 4"))
        self.Text_area.setText(_translate("MainWindow", "Your text will be displayed here.."))
        self.label_7.setText(_translate("MainWindow", "OK"))
        self.menud2d2d2d2d2d2.setTitle(_translate("MainWindow", "Assist"))

        
#my functions
class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def keyPressEvent(self, event):
        if event.key() == QtCore.Qt.Key_A:
            print("Key A pressed")
        elif event.key() == QtCore.Qt.Key_B:
            print("Key B pressed")
        else:
            print(f"Key {event.key()} pressed")

    
    
'''

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

'''

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = MainWindow()
    window.show()
    sys.exit(app.exec_())

    
